version: "3"
services:
  nginx:
    image: nginx
    environment:
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d